name: Deliver Tokens To Consumer 

on:
  push:
    paths:	
      - 'build/**'

jobs:
  # Add a job for every additional consumer/application
  deliver_to_react_application:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Deliver Platform Deliverable To Application
      uses: andstor/copycat-action@v3
      with:
        # See documentation: https://docs.github.com/en/actions/reference/encrypted-secrets
        # Set the secret in the "src" repository
        personal_token: ${{ secrets.API_TOKEN_GITHUB }}
        # You may need to change this to "main"
        src_branch: master
        src_path: build/js/_variables.js
        # Replace with your repository owner. Most likely, this is your GitHub username.
        dst_owner: michaelmang
        dst_repo_name: consume-style-dictionary-github-actions
        # You may need to change this to "main"
        dst_branch: master
        dst_path: tokens/_variables.js
        commit_message: Update design tokens